#Configuration for failfast=false

info:
  component: Turbine
  
# HTTP Server
server:
  port: ${TURBINE_PORT:9898}

turbine:
  stream:
    port: 8989
  
management:
  port: -1

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: cygnusStream
#          content-type: application/json
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
    org.springframework.integration: DEBUG

