# HTTP Server
server:
  port: ${PORT:9999}   # HTTP port
  
# Discovery Server Access

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}
  instance:
     preferIpAddress: true
