#Configuration for failfast=false

# HTTP Server
server:
  port: 3333
  
#management:
#  context-path: /sadr

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

management:
  security:
    enabled: false
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cygnus:
  deneb:
    name: deneb
    pingUrl: http://${cygnus.deneb.name}/ping/

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


     