#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:2222}   # HTTP port
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'DEBUG'
    com.atsistemas: 'DEBUG'

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

cygnus:
  sadr:
    name: sadr
    pingUrl: http://${cygnus.sadr.name}/ping/
    pingDelay: 1000

spring:
   rabbitmq:
     host: rabbitmq
     port: 5672
     username: guest
     password: guest
