#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:1111}   # HTTP port
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 

