#Configuration for failfast=false

# HTTP Server
server:
  port: ${EUREKA_SERVER_PORT:1111}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

management:
  security:
    enabled: false

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 

